### ISSUE TITLE
Rendering large text

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#67] opened 2020-07-15 20:19 UTC
Hi, it's me again, looks like some bits and pieces of mark up are getting rendered as a header for no apparent reason. Here's an example:

<img width="1203" alt="Screen Shot 2020-07-15 at 10 17 37 PM" src="https://user-images.githubusercontent.com/35434644/87591823-33629600-c6e9-11ea-8abc-16426107d249.png">
<img width="593" alt="Screen Shot 2020-07-15 at 10 17 46 PM" src="https://user-images.githubusercontent.com/35434644/87591827-3493c300-c6e9-11ea-9f43-d0e4696f0c93.png">

**Comment by kallewesterling** [comment] 2020-07-17 14:02
Can you check and see if it works better now? I've started to use GitHub's own API for translation of markdown into HTML and it is more aligned with how the text lives in the repositories now... (I hope!)

**Comment by smorello87** [comment] 2020-07-18 08:53
Thank you, K! I still see it rendered in the same way, though. I also noticed that some line breaks (especially near my images) are not rendered correctly. I tried to add a few `<br>` but to no avail

**Comment by smorello87** [comment] 2020-07-18 08:55
Here are a couple of examples

1) <img width="1073" alt="Screen Shot 2020-07-18 at 10 29 27 AM" src="https://user-images.githubusercontent.com/35434644/87848930-f6fb8980-c8e4-11ea-8dec-e9cb94b0f9a1.png">

<img width="1228" alt="Screen Shot 2020-07-18 at 10 49 54 AM" src="https://user-images.githubusercontent.com/35434644/87848932-fb27a700-c8e4-11ea-9ac9-830894e9b3a4.png">

2) 
<img width="1188" alt="Screen Shot 2020-07-18 at 10 50 31 AM" src="https://user-images.githubusercontent.com/35434644/87848944-14c8ee80-c8e5-11ea-8c68-9bb8e10c2966.png">

3) (This is another example of large text) 
<img width="1168" alt="Screen Shot 2020-07-18 at 10 50 42 AM" src="https://user-images.githubusercontent.com/35434644/87848951-2f02cc80-c8e5-11ea-9b5e-097d4cf48c09.png">

**Comment by kallewesterling** [comment] 2020-07-20 14:33
I can see now what the problem is. I have to fix something in the ingestion process - so this is a bug on my end. Opening an issue for myself in the `django-app`!

**Comment by kallewesterling** [comment] 2020-07-22 21:07
I'm going ahead and closing this issue here, since it's a bug related to the website and not specific to this workshop.

**Closed as completed by kallewesterling** 2020-07-22 21:07 UTC
